#!/usr/bin/env node

const { app, BrowserWindow, ipcMain } = require("electron");
const fs = require("file-system");
const fetch = require("node-fetch");
const path = require("path");
let mainWindow;

function rimraf(dir_path) {
  if (fs.existsSync(dir_path)) {
    fs.readdirSync(dir_path).forEach(function(entry) {
      var entry_path = path.join(dir_path, entry);
      if (fs.lstatSync(entry_path).isDirectory()) {
        rimraf(entry_path);
      } else {
        fs.unlinkSync(entry_path);
      }
    });
    fs.rmdirSync(dir_path);
  }
}

fs.readdir(path.join(__dirname, "events"), function(err, folders) {
  folders.forEach(folder => {
    fs.readdir(path.join(__dirname, "events", folder), function(err, files) {
      files.forEach(file => {
        let name = file.split(".")[0];
        ipcMain.on(name, function() {
          require(path.join(__dirname, "events", folder, file))(mainWindow);
        });
      });
    });
  });
});

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 700,
    webPreferences: {
      nodeIntegration: true
    },
    frame: false,
    titleBarStyle: "hiddenInset"
  });

  mainWindow.loadFile(path.resolve(__dirname + "/web/index.html"));
  mainWindow.on("closed", function() {
    mainWindow = null;
  });
}

app.on("ready", createWindow);

app.on("window-all-closed", function() {
  if (process.platform !== "darwin") app.quit();
});

app.on("activate", function() {
  if (mainWindow === null) createWindow();
});
